version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      # - eb/setup
      - aws-cli/setup

      - run:
          name: Frontend Install
          command: npm run frontend:install

      - run:
          name: Frontend Build
          command: npm run frontend:build

      - run:
          name: Backend Install
          command: npm run backend:install

      - run:
          name: Backend Build
          command: npm run backend:build

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE

          from: udagram-frontend/www
          to: 's3://fullstack-udagram/'

      # - run:
      #     command: |
      #         # eb create Udagram-env
      #         eb deploy Udagram-env
      #         eb status
      #     working_directory: <<udagram/www>>

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
