version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-s3: circleci/aws-s3@3.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14

# parameters:
#   app-dir:
#     default: .
    steps:
      - checkout
      - eb/setup
      - aws-cli/setup

      # - run:
      #     name: Frontend Install
      #     command: npm run frontend:install

      # - run:
      #     name: Frontend Build
      #     command: npm run frontend:build

      - run:
          name: Backend Install
          command: npm run backend:install

      - run:
          name: Backend Build
          command: npm run backend:build

      # - aws-s3/sync:
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"

          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE

          # from: udagram-frontend/www
          # to: 's3://fullstack-udagram/'
    
      - run:
          name: deploy backend
          command: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            aws s3 mv ./udagram-api/www/Archive.zip s3://elasticbeanstalk-us-east-1-917621399440/app/app-dev-$TIMESTAMP.zip
            aws elasticbeanstalk create-application-version --region us-east-1 \
              --application-name udagram --version-label development-$TIMESTAMP \
              --source-bundle S3Bucket=elasticbeanstalk-us-east-1-917621399440,S3Key=app/app-dev-$TIMESTAMP.zip
            aws elasticbeanstalk update-environment --region us-east-1 --environment-name Udagram-env \
              --version-label development-$TIMESTAMP

      
          # name: eb set up
          # command: |
          #     eb init
          #     eb deploy Udagram-env --region us-east-1
          #     eb status
          # working_directory: udagram/www

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
