version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - aws-cli/setup

      - run:
          name: Frontend Install
          command: npm run frontend:install

      - run:
          name: Frontend Build
          command: npm run frontend:build

      - run:
          name: Frontend Test
          command: npm run frontend:test

      - run:
          name: Backend Install
          command: npm run backend:install

      - run:
          name: Backend Build
          command: npm run backend:install

      - run:
          name: Backend Test
          command: npm run backend:test

      - run:
          name: Frontend Deploy
          command: npm run frontend:deploy

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout

      - run:
          name: Create a Bucket Directory
          command: mkdir bucket && echo "Hello World" > bucket/build_asset.txt

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: bucket
          to: 's3://fullstack-udagram/prefix'

      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://fullstack-udagram'

workflows:
  Deployment Project:
    jobs:
      - build
      - deploy

      - deploy:
          requires:
            - build
        filters:
          branches:
            only: master
