version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - aws-cli/setup

      - run:
          name: Run install frontend
          command: npm run frontend:install

      - run:
          name: Run Build frontend
          command: npm run frontend:build

      - run:
          name: Run install backend
          command: npm run backend:install

      - run:
          name: Run Build backend
          command: npm run backend:build

  deploy:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout

      - run:
          name: Run deploy
          command: npm run frontend:deploy

workflows:
  udagram:
    jobs:
      - build
      - deploy
