version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - node/install
      - checkout
      - aws-cli/setup

      - run:
          name: Frontend install
          command: npm run frontend:install

      - run:
          name: Frontend Build
          command: npm run frontend:build

      - run:
          name: Backend install
          command: npm run backend:install

      - run:
          name: Backend Build
          command: npm run backend:build

      - run:
          name: Run deploy
          command: npm run frontend:deploy

  # deploy:
  #   docker:
  #     - image: cimg/node:16.14
  #   steps:
  #     - checkout

  #     - run:
  #         name: Run deploy
  #         command: npm run frontend:deploy

workflows:
  udagram:
    jobs:
      - build
      # - deploy
