version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
<<<<<<< HEAD
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

=======
  aws-s3: circleci/aws-s3@3.0
>>>>>>> d0ebf223a4e1b95b6af0db5fe08ccdad3ad284ee
jobs:
  build:
    docker:
      - image: cimg/node:16.14

    steps:
      - checkout
      - aws-cli/setup
      - eb/setup

      - run:
          name: Frontend Install
          command: npm run frontend:install

      - run:
          name: Frontend Build
          command: npm run frontend:build

      - run:
          name: Backend Install
          command: npm run backend:install

      - run:
          name: Backend Build
          command: npm run backend:build

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: udagram-frontend/www
          to: 's3://fullstack-udagram/'

      - run:
          command: |
              eb create my-environment
              eb deploy my-environment
              eb status

workflows:
  deploy project:
    jobs:
      - build:
          filters:
            branches:
              only: master
