version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  deploy:
    docker:
      - image: cimg/node:16.14

    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - aws-cli/setup

      - run:
          name: Frontend install
          command: npm run frontend:install

      - run:
          name: Frontend Build
          command: npm run frontend:build

      # - run:
      #     name: Frontend Test
      #     command: npm run frontend:test

      - run:
          name: Backend install
          command: npm run backend:install

      # - run:
      #     name: Backend Test
      #     command: npm run backend:test

      - run:
          name: Run deploy
          command: npm run frontend:deploy

      - run:
          name: Upload file to S3
          command: aws s3 sync ./www/ s3://fullstack-udagram --delete

workflows:
  udacity project:
    jobs:
      - deploy
